name: Build SAC x86_64/amd64 Intel CPU macOS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Git clone vvdec
      run: git clone --depth=1 https://github.com/MartinEesmaa/sac
    - name: Build sac
      run: cd sac/src && clang++ main.cpp cmdline.cpp ./common/*.cpp ./file/*.cpp ./libsac/*.cpp ./model/*.cpp ./pred/*.cpp -std=c++11 -static -O2 -osac_x64 -target x86_64-apple-macos10.12 && cd ../../
    - name: Zip Release of sac
      uses: TheDoctor0/zip-release@0.7.1
      with:
        filename: sac.zip
        path: ./sac/src
    - name: Upload a Build Artifact of SAC
      uses: actions/upload-artifact@v3.0.0
      with:
        name: sac_x64
        path: ./sac.zip
