name: Check target macOS available using LLC from LLVM
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Scan all macOS targets and print it out
      run: clang++ -print-targets
